openapi: 3.0.0
info:
  title: Analytics
  version: '0.1'
  description: |-
    The Analytics API provides endpoints for querying current state, historical trends and summarisations of an environment and interactions within it.

    It is currently within an early release phase and will undergo regular breaking changes.

    **Not recommended for production use.**
servers:
  - url: 'https://place.ll-uat.aca.im'
    variables:
      host:
        default: place.ll-uat.aca.im
        description: Host where place is deployed.
    description: UAT infrastructure
paths:
  '/location/{id}/presence':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Location ID to query
    get:
      summary: Location Presence
      tags:
        - presence
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                title: aggregate
                type: object
                x-examples: {}
                properties:
                  value:
                    type: number
                    description: Predicted presence at the requested time
                    enum:
                      - 0
                      - 1
                  confidence:
                    type: number
                    minimum: 0
                    maximum: 1
                required:
                  - value
              examples:
                Example:
                  value:
                    value: 1
        '204':
          description: No event data is available for the time requested. This will occur if `at` is prior to any data being available.
      operationId: get-location-id-presence
      description: Provides presence insights for a location.
      security:
        - API Key: []
      parameters:
        - schema:
            type: string
          in: query
          name: at
          description: A point in time (RFC3339) to query.
          required: true
        - schema:
            type: string
            enum:
              - daily
              - weekly
              - fortnightly
              - monthly
              - yearly
          in: query
          name: window
          description: Seasonality window to use for predictions.
        - schema:
            type: string
          in: query
          name: from
          description: A source type (e.g. `camera`). If specified only events from this type will be used.
  '/location/{id}/state/{event}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Location identifier
      - schema:
          type: string
        name: event
        in: path
        required: true
        description: Event type
    get:
      summary: Location Parameter History
      operationId: get-location-id-state-event
      responses:
        '200':
          description: The state at the requested time.
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: number
        '204':
          description: No data availble for the requested time.
        '400':
          description: Bad Request. Returned if `at` is in the future.
      tags:
        - state
        - location
      description: Query the state of a tracked parameter at a specific point in time.
      parameters:
        - schema:
            type: string
          in: query
          name: at
          description: An RFC3339 timestamp. If excluded `now` is assumed.
        - schema:
            type: string
          in: query
          name: from
          description: Filter to a specific source type.
  '/location/{id}/utilisation':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Location ID
    get:
      summary: Location Utilisation
      tags:
        - utilisation
        - location
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: number
                    minimum: 0
                    maximum: 1
                    description: Utilization level over the time window
                required:
                  - value
      operationId: get-location-id-utilization
      description: |-
        Utilization insights for a location.

        This combines together multiple signals (presence, people_count, in_use etc) to provide utilization metrics.
      parameters:
        - schema:
            type: string
          in: query
          name: start
        - schema:
            type: string
          in: query
          name: stop
components:
  schemas:
    rfc3339:
      type: string
      title: RFC3339
      pattern: "/^(?<fullyear>\\d{4})-(?<month>0[1-9]|1[0-2])-(?<mday>0[1-9]|[12][0-9]|3[01])T(?<hour>[01][0-9]|2[0-3]):(?<minute>[0-5][0-9]):(?<second>[0-5][0-9]|60)(?<secfrac>\\.[0-9]+)?(Z|(\\+|-)(?<offset_hour>[01][0-9]|2[0-3]):(?<offset_minute>[0-5][0-9]))$/i"
      description: 'An [RFC3339](https://tools.ietf.org/html/rfc3339) date-time string'
      x-examples:
        Example: '2018-01-29T20:36:30+00:00'
  securitySchemes:
    API Key:
      name: X-API-Key
      type: apiKey
      in: header
      description: ''
tags:
  - name: metadata
    description: Queries providing metadata about a tracked entity
  - name: location
    description: Location queries
  - name: level
    description: Level queries
  - name: building
    description: Building queries
  - name: organisation
    description: Organistaion queries
  - name: state
    description: Queries providing historical state.
  - name: presence
    description: Presence insights
  - name: utilisation
    description: Utilisation insights
