openapi: 3.0.0
info:
  title: Analytics
  version: '0.3'
  description: |-
    The Analytics API provides endpoints for querying current state, historical trends and summarisations of an environment and interactions within it.

    It is currently within an early release phase and will undergo regular breaking changes.

    **Not recommended for production use.**
servers:
  - url: 'https://place.ll-uat.aca.im'
    variables:
      host:
        default: place.ll-uat.aca.im
        description: Host where place is deployed.
    description: UAT infrastructure
paths:
  '/location/{id}/occupancy':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Location ID to query
    get:
      summary: Location Occupancy
      responses:
        '200':
          description: ''
          headers: {}
      operationId: get-location-id-occupancy
      description: |-
        Provide occupancy metrics for a location.

        Occupancy is an an indicator of human usage of locations. A location is considered occupied when a person is physically there and using it. A location which has had materials left (laptops, paper etc), but no person present is considered un-occupied.
      security:
        - API Key: []
      parameters:
        - schema:
            type: string
          in: query
          name: start
          description: An RFC3339 timestamp with the start of the query range
          required: true
        - schema:
            type: string
          in: query
          name: stop
          description: An RFC3339 timestamp with the end of the query range
          required: true
        - schema:
            type: string
          in: query
          name: every
      tags:
        - occupancy
  '/level/{id}/occupancy':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Level Occupancy
      tags:
        - occupancy
      responses:
        '200':
          description: OK
      operationId: get-level-id-occupancy
      description: |-
        Provide occupancy metrics, agreggated for a level within a building.

        Occupancy is an an indicator of human usage of locations. A location is considered occupied when a person is physically there and using it. A location which has had materials left (laptops, paper etc), but no person present is considered un-occupied.
      security:
        - API Key: []
      parameters:
        - schema:
            type: string
          in: query
          name: start
          required: true
          description: An RFC3339 timestamp with the start of the query range
        - schema:
            type: string
          in: query
          name: stop
          required: true
          description: An RFC3339 timestamp with the end of the query range
        - schema:
            type: string
          in: query
          name: every
          description: ''
        - schema:
            type: string
          in: query
          name: group_by
  '/building/{id}/occupancy':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Building Occupancy
      tags:
        - occupancy
      responses:
        '200':
          description: OK
      operationId: get-building-id-occupancy
      security:
        - API Key: []
      parameters:
        - schema:
            type: string
          in: query
          name: start
          description: An RFC3339 timestamp with the start of the query range
          required: true
        - schema:
            type: string
          in: query
          name: stop
          description: An RFC3339 timestamp with the end of the query range
          required: true
        - schema:
            type: string
          in: query
          name: every
        - schema:
            type: string
          in: query
          name: group_by
      description: |
        Provide occupancy metrics, agreggated at the building level.

        Occupancy is an an indicator of human usage of locations. A location is considered occupied when a person is physically there and using it. A location which has had materials left (laptops, paper etc), but no person present is considered un-occupied.
  '/organisation/{id}/occupancy':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Organisation Occupancy
      tags:
        - occupancy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - type: number
                    description: Singular aggregation for the time range
                  - type: array
                    description: Regular time series
                    items:
                      type: number
                  - type: object
                    description: Aggregations grouped by a location attribute
      operationId: get-organisation-id-occupancy
      security:
        - API Key: []
      parameters:
        - schema:
            type: string
          in: query
          name: start
          description: An RFC3339 timestamp with the start of the query range
          required: true
        - schema:
            type: string
          in: query
          name: stop
          required: true
          description: An RFC3339 timestamp with the end of the query range
        - schema:
            type: string
            pattern: 'd+[smhdwy]'
          in: query
          name: every
          description: Time interval to provide values for within the range
        - schema:
            type: string
          in: query
          name: group_by
          description: ''
      description: |-
        Provide occupancy metrics, agreggated for an organisation.

        Occupancy is an an indicator of human usage of locations. A location is considered occupied when a person is physically there and using it. A location which has had materials left (laptops, paper etc), but no person present is considered un-occupied.
  '/location/{id}/raw/{event}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Location identifier
      - schema:
          type: string
        name: event
        in: path
        required: true
        description: Event type
    get:
      summary: Location Parameter History
      operationId: get-location-id-state-event
      responses:
        '200':
          description: The state at the requested time.
          content:
            application/json:
              schema:
                type: number
        '400':
          description: Bad Request. Returned if `at` is in the future.
        '':
          content:
            application/json:
              schema:
                type: number
                description: The value of the tracked parameter at the requested time
      description: Query the state of a tracked parameter at a specific point in time.
      parameters:
        - schema:
            type: string
          in: query
          name: at
          description: An RFC3339 timestamp. If excluded `now` is assumed.
        - schema:
            type: string
          in: query
          name: src
          description: Filter to a specific source type.
      tags:
        - history
components:
  schemas:
    rfc3339:
      type: string
      title: RFC3339
      pattern: "/^(?<fullyear>\\d{4})-(?<month>0[1-9]|1[0-2])-(?<mday>0[1-9]|[12][0-9]|3[01])T(?<hour>[01][0-9]|2[0-3]):(?<minute>[0-5][0-9]):(?<second>[0-5][0-9]|60)(?<secfrac>\\.[0-9]+)?(Z|(\\+|-)(?<offset_hour>[01][0-9]|2[0-3]):(?<offset_minute>[0-5][0-9]))$/i"
      description: 'An [RFC3339](https://tools.ietf.org/html/rfc3339) date-time string'
      x-examples:
        Example: '2018-01-29T20:36:30+00:00'
  securitySchemes:
    API Key:
      name: X-API-Key
      type: apiKey
      in: header
      description: ''
tags:
  - name: metadata
    description: Queries providing metadata about a tracked entity
  - name: location
    description: Location queries
  - name: level
    description: Level queries
  - name: building
    description: Building queries
  - name: organisation
    description: Organistaion queries
  - name: history
    description: Queries providing historical state.
  - name: occupancy
    description: Occupancy insights
  - name: utilisation
    description: Utilisation insights
