openapi: 3.0.0
info:
  title: Metadata
  version: '1.0'
  description: 'The Metadata API provides addition information and context about location, level, buildings and organisations.'
servers:
  - url: 'https://place.ll-uat.aca.im'
    description: UAT infrastructure
paths:
  '/location/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Query Location Metadata
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location'
        '404':
          description: Not Found
      operationId: get-location-id
      description: Retrieves metadata available for a location.
      tags:
        - location
      security:
        - X-API-Key: []
components:
  schemas:
    location:
      title: Location
      type: object
      description: |-
        Metadata associated with a location.

        Additional keys may exist containing supplementary metadata propogated by the originating system.
      properties:
        id:
          type: string
          description: Globally unique identifier for this location.
        level:
          type: string
          description: Identifier of the level this location is in.
        building:
          type: string
          description: Identifier of the building this location is in.
        organisation:
          type: string
          description: Identifier of the organisation this location belongs to.
        capacity:
          type: integer
          description: Number of people this location accomodates.
        bookable:
          type: boolean
          description: True if usage can be reserved.
      required:
        - id
        - level
        - building
        - organisation
  securitySchemes:
    X-API-Key:
      name: API Key
      type: apiKey
      in: header
tags: location level building organisation
