openapi: 3.0.0
info:
  title: Metadata
  version: '1.0'
  description: 'The Metadata API provides addition information and context about location, level, buildings and organisations.'
servers:
  - url: 'https://place.ll-uat.aca.im'
    description: UAT infrastructure
paths:
  '/location/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Query Location Metadata
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location'
        '404':
          description: The requested location is not tracked by this system.
      operationId: get-location-id
      description: Retrieves metadata available for a location.
      tags:
        - location
      security:
        - X-API-Key: []
  '/level/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Query Level Metadata
      tags:
        - level
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/level'
        '404':
          description: The requested level is not tracked by this system.
      operationId: get-level-id
      description: Retrieves metedata available for a level.
      security:
        - X-API-Key: []
  '/building/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Query Building Metadata
      tags:
        - building
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/building'
        '404':
          description: The requested building is not tracked by this system.
      operationId: get-building-id
      description: Retrieves metadata available for a building.
      security:
        - X-API-Key: []
  '/organisation/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Query Organisation Metadata
      tags:
        - organisation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organisation'
        '404':
          description: The requested location is not tracked by this system.
      operationId: get-organisation-id
      description: Retrieves metedata available for an organisation.
      security:
        - X-API-Key: []
  '/organisation/{id}/buildings':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: List Buildings
      tags:
        - organisation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/building'
      operationId: get-organisation-id-buildings
      description: Retrieve all buildings within an organisation.
      security:
        - X-API-Key: []
  '/building/{id}/levels':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: List Levels
      tags:
        - building
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/level'
      operationId: get-building-id-levels
      security:
        - X-API-Key: []
      description: List all levels within a building.
  '/level/{id}/locations':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: List Locations
      tags:
        - level
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/location'
      operationId: get-level-id-locations
      security:
        - X-API-Key: []
components:
  schemas:
    location:
      title: Location Model
      type: object
      description: |-
        Metadata associated with a location.

        Additional keys may exist containing supplementary metadata propogated by the originating system.
      properties:
        id:
          type: string
          description: Globally unique identifier.
        level:
          type: string
          description: Identifier of the level this location is in.
        building:
          type: string
          description: Identifier of the building this location is in.
        organisation:
          type: string
          description: Identifier of the organisation this location belongs to.
        capacity:
          type: integer
          description: Number of people this location accomodates.
          minimum: 0
        bookable:
          type: boolean
          description: True if usage can be reserved.
        name:
          type: string
        email:
          type: string
          format: email
          description: Resource URI associated with booking systems
        description:
          type: string
        type:
          type: string
          description: ''
      required:
        - id
        - level
        - building
        - organisation
        - name
    level:
      title: Level Model
      type: object
      description: Additional keys may exist containing supplementary metadata propogated by the originating system.
      properties:
        id:
          type: string
          description: Globally unique identifier.
        building:
          type: string
          description: Identifier for the building this level is in.
        organisation:
          type: string
          description: Identifier for the organisations this level belongs to.
        name:
          type: string
        description:
          type: string
        locations:
          type: array
          description: "List of location ID's within on this level"
          items:
            type: string
      required:
        - id
        - building
        - organisation
        - name
        - description
        - locations
    building:
      title: Building Model
      type: object
      description: Additional keys may exist containing supplementary metadata propogated by the originating system.
      properties:
        id:
          type: string
          description: Globally unique identifier
        organisation:
          type: string
          description: Identifier of the organisation this building belongs to
        levels:
          type: array
          description: "List of level ID's wihin this building"
          items:
            type: string
        description:
          type: string
        name:
          type: string
      required:
        - id
        - organisation
        - levels
        - description
        - name
    organisation:
      title: Organisation Model
      type: object
      description: Additional keys may exist containing supplementary metadata propogated by the originating system.
      properties:
        id:
          type: string
          description: Globally unique identifier.
        name:
          type: string
        description:
          type: string
        buildings:
          type: array
          description: "List of builing ID's belonging to this organisation"
          items:
            type: string
      required:
        - id
        - name
        - buildings
  securitySchemes:
    X-API-Key:
      name: API Key
      type: apiKey
      in: header
tags:
  - name: location
  - name: level
  - name: building
  - name: organisation
